//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcStok.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblSatıs
    {
        public int satısıd { get; set; }
        public Nullable<int> urunıd { get; set; }
        public Nullable<int> musteriıd { get; set; }
        public Nullable<short> kategoriıd { get; set; }
        public Nullable<decimal> fiayt { get; set; }
    
        public virtual TblMusteriler TblMusteriler { get; set; }
        public virtual TblUrunler TblUrunler { get; set; }
    }
}
